# Generated by Django 5.0.3 on 2024-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0002_usercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='', upload_to='static/visitingcard')),
            ],
        ),
    ]
