# Generated by Django 5.0.3 on 2024-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0003_visitingcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitingcard',
            name='image',
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='back_image',
            field=models.ImageField(default='', upload_to='static/visitingcard'),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='front_image',
            field=models.ImageField(default='', upload_to='static/visitingcard'),
        ),
    ]
