# Generated by Django 5.0.3 on 2024-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0006_remove_visitingcard_visitingcard_id_visitingcard_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000)),
                ('front_image', models.ImageField(default='', upload_to='static/idcard')),
            ],
        ),
    ]
