# Generated by Django 5.0.3 on 2024-04-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0008_rename_front_image_idcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
