# Generated by Django 5.0.3 on 2024-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0009_alter_idcard_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='static/idcard')),
            ],
        ),
    ]
