# Generated by Django 4.2.13 on 2024-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmaker', '0010_bussinesscard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='static/resume')),
            ],
        ),
        migrations.DeleteModel(
            name='BussinessCard',
        ),
    ]
